services:
  test_env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_env_cont
    env_file:
      - .env
    volumes:
      - ./allure-results:/app/allure-results    # результат от pytest
      - ./allure-report:/app/allure-report      # готовый HTML отчёт
    command: >
      /bin/bash -c "
      pytest --alluredir=/app/allure-results &&
      allure generate /app/allure-results -o /app/allure-report --clean
      "