BASE_URL = "https://www.saucedemo.com"
INVENTORY = f"{BASE_URL}/inventory.html"
CART = f"{BASE_URL}/cart.html"
CHECKOUT_STEP_1 = f"{BASE_URL}/checkout-step-one.html"
CHECKOUT_STEP_2 = f"{BASE_URL}/checkout-step-two.html"
CHECKOUT_COMPLETE = f"{BASE_URL}/checkout-complete.html"
